// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package kopfbisfuss.universal;

public final class DienstServerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements kopfbisfuss.universal.DienstServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getDienst_0;
    private static java.lang.reflect.Method $method_getDienstListe_1;
    
    static {
	try {
	    $method_getDienst_0 = kopfbisfuss.universal.DienstServer.class.getMethod("getDienst", new java.lang.Class[] {java.lang.Object.class});
	    $method_getDienstListe_1 = kopfbisfuss.universal.DienstServer.class.getMethod("getDienstListe", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public DienstServerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getDienst(Object)
    public kopfbisfuss.universal.Dienst getDienst(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDienst_0, new java.lang.Object[] {$param_Object_1}, 1554828120351928322L);
	    return ((kopfbisfuss.universal.Dienst) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDienstListe()
    public java.lang.Object[] getDienstListe()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDienstListe_1, null, 2597100337426766514L);
	    return ((java.lang.Object[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
